#!/usr/bin/perl -w
#!/usr/bin/perl -d:ptkdb -w
#

use strict;


$| = 1;


BEGIN
{
    push @INC, './perl';

    push @INC, '/usr/local/glue/swig/perl';
}


use Data::Dumper;

use SSP;


$SIG{__DIE__}
    = sub {
	use Carp;

	confess @_;
    };

$ENV{NEUROSPACES_MODELS} = '/local_home/local_home/hugo/neurospaces_project/neurospaces/source/c/snapshots/0/library';


sub main
{
    # model specification array

    my $args = [ "$0", "-P", "tests/cells/tensizesp.ndf" ];

    # instantiate a scheduler

    my $scheduler
	= SSP->new(
		   {
		    apply => {
			      simulation => [
					     {
					      arguments => [ 10, 1, ],
					      method => 'steps',
					     },
					     {
					      arguments => [ 0.1, ],
					      method => 'advance',
					     },
					    ],
			     },
		    models => [
			       {
				modelname => "/tensizesp",
				solverclass => "heccer",
			       },
			      ],
		    name => 'tensizesp',
		    services => {
				 neurospaces => {
						 initializers => [
								  {
								   arguments => [ $#$args + 1, $args, ],
								   method => 'read',
								  },
								 ],
						 module_name => 'Neurospaces',
						},
				},
		    solverclasses => {
				      heccer => {
						 module_name => 'Heccer',
						 service_name => 'neurospaces',
						},
				     },
		   },
		  );

    # run the schedule

    $scheduler->run();
}


main();


exit 0;


