#!/usr/bin/perl -w
#!/usr/bin/perl -d:ptkdb -w
#

use strict;


$| = 1;


BEGIN
{
    #! make check

    push @INC, '../perl';

    #! make distcheck

    push @INC, '../../perl';

    #! normal run

    push @INC, './perl';

    #! after install

    push @INC, '/usr/local/glue/swig/perl';
}


use SwiggableHeccer;

use SSP;


$SIG{__DIE__}
    = sub {
	use Carp;

	confess @_;
    };

$ENV{NEUROSPACES_NMC_MODELS} = '/usr/local/neurospaces/models/library';


sub main
{
    # model specification array

    my $modelname = $0;

    $modelname =~ s/.*\///;

    $modelname =~ s/-/_/g;

    my $args = [ "$0", "-P", "tests/cells/$modelname.ndf" ];

    # instantiate a scheduler

    my $scheduler
	= SSP->new(
		   {
		    apply => {
			      simulation => [
					     {
					      arguments => [ 1, { verbose => 2, }, ],
					      method => 'steps',
					     },
					     {
					      arguments => [ 0.1, ],
					      method => 'advance',
					     },
					    ],
			     },
		    models => [
			       {
				modelname => "/$modelname",
				solverclass => "heccer",
			       },
			      ],
		    name => $modelname,
		    services => {
				 model_container => {
						     initializers => [
								      {
								       arguments => [ $args, ],
								       method => 'read',
								      },
								     ],
						     module_name => 'Neurospaces',
						    },
				},
		    solverclasses => {
				      heccer => {
						 constructor_settings => {
									  configuration => {
											    reporting => {
													  tested_things => ($SwiggableHeccer::HECCER_DUMP_TABLE_GATE_TABLES
															    | $SwiggableHeccer::HECCER_DUMP_TABLE_GATE_SUMMARY
															    | $SwiggableHeccer::HECCER_DUMP_VM_MECHANISM_DATA
															    | $SwiggableHeccer::HECCER_DUMP_INTERMEDIARY_SUMMARY
															    | $SwiggableHeccer::HECCER_DUMP_INTERMEDIARY_STRUCTURE
															    | $SwiggableHeccer::HECCER_DUMP_INTERMEDIARY_COMPARTMENTS_PARAMETERS
															    | $SwiggableHeccer::HECCER_DUMP_INDEXERS_SUMMARY
															    | $SwiggableHeccer::HECCER_DUMP_INDEXERS_STRUCTURE
															    | $SwiggableHeccer::HECCER_DUMP_VM_MECHANISM_OPERATIONS
															    | $SwiggableHeccer::HECCER_DUMP_VM_COMPARTMENT_MATRIX_DIAGONALS
															    | $SwiggableHeccer::HECCER_DUMP_VM_COMPARTMENT_MATRIX
															    | $SwiggableHeccer::HECCER_DUMP_VM_AGGREGATORS
															    | $SwiggableHeccer::HECCER_DUMP_VM_COMPARTMENT_OPERATIONS),
													 },
											   },
									  options => {
										      dIntervalEnd => 0.05,
										      dIntervalStart => -0.1,
										      iIntervalEntries => 50,
										     },
									 },
						 module_name => 'Heccer',
						 service_name => 'model_container',
						},
				     },
		   },
		  );

    use YAML;

    my $scheduler_yaml;

    {
	local $/;

	if (-e "./yaml/$modelname.yml")
	{
	    $scheduler_yaml = Load(`cat ./yaml/$modelname.yml`);
	}
    }

    # run the schedule

    $scheduler->run();
}


main();


exit 0;


